CREATE TABLE adres(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gml_id VARCHAR(255) NOT NULL,
    miejscowosc VARCHAR(255) NOT NULL,
    ulica VARCHAR(255) NOT NULL,
    nr_porzadkowy VARCHAR(255) NOT NULL
    );

CREATE TABLE transakcja(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rcn VARCHAR(255) NOT NULL,
    rodzaj_transakcji INT NOT NULL,
    rodzaj_rynku INT NOT NULL,
    strona_sprzedajaca INT NOT NULL,
    strona_kupujaca INT NOT NULL,
    cena_transakcji DECIMAL NOT NULL,
    data_sporzadzenia_dokumentu DATE NOT NULL,
    rodzaj_prawa_wlasnosci INT NOT NULL,
    udzial_w_nieruchomosci TEXT NOT NULL,
    pole_powierzchni_gruntowej NUMERIC,
    cena_nieruchomosci DECIMAL,
    rodzaj_nieruchomosci INT,
    FOREIGN KEY (rodzaj_transakcji) REFERENCES rodzaj_transakcji(id),
    FOREIGN KEY (rodzaj_rynku) REFERENCES rodzaj_rynku(id),
    FOREIGN KEY (strona_sprzedajaca) REFERENCES strona_transakcji(id),
    FOREIGN KEY (strona_kupujaca) REFERENCES strona_transakcji(id),
    FOREIGN KEY (rodzaj_prawa_wlasnosci) REFERENCES rodzaj_prawa_wlasnosci(id)
    );

CREATE TABLE dzialka(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rcn VARCHAR(255) NOT NULL,
    pole_powierzchni_ewidencyjnej NUMERIC NOT NULL,
    sposob_uzytkowania INT,
    cena_dzialki_ewidencyjnej DECIMAL,
    dodatkowe_informacje TEXT,
    FOREIGN KEY (sposob_uzytkowania) REFERENCES sposob_uzytkowania(id)
    );

CREATE TABLE budynek(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rcn VARCHAR(255) NOT NULL,
    rodzaj_budynku INT NOT NULL,
    powierzchnia_uzytkowa NUMERIC,
    cena_budynku DECIMAL,
    dodatkowe_informacje TEXT,
    FOREIGN KEY (rodzaj_budynku) REFERENCES rodzaj_budynku(id)
    );

CREATE TABLE lokal(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rcn VARCHAR(255) NOT NULL,
    funkcja_lokalu INT NOT NULL,
    liczba_izb INT NOT NULL,
    nr_kondygnacji INT NOT NULL,
    powierzchnia_uzytkowa_lokalu NUMERIC NOT NULL,
    powierzchnia_uzytkowa_pomieszczen_przynal NUMERIC,
    cena_lokalu DECIMAL,
    dodatkowe_informacje TEXT,
    FOREIGN KEY (funkcja_lokalu) REFERENCES funkcja_lokalu(id)
    );

    CREATE TABLE identyfikator(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gml_id VARCHAR(255) NOT NULL,
    id_transakcji INT NOT NULL,
    id_dzialki INT,
    id_budynku INT,
    id_lokalu INT,
    id_adresu INT,
    FOREIGN KEY (id_transakcji) REFERENCES transakcja(id),
    FOREIGN KEY (id_dzialki) REFERENCES dzialka(id),
    FOREIGN KEY (id_budynku) REFERENCES budynek(id),
    FOREIGN KEY (id_lokalu) REFERENCES lokal(id),
    FOREIGN KEY (id_adresu) REFERENCES adres(id)
    );